### ISSUE TITLE
小米14刷入后无法使用根证书

### ISSUE THREAD

**Issue by kafuunochino** [wjf0214/Magisk-MoveCACerts#1]
小米14刷入后无法使用根证书,刷入后把hash.0的文件放入/data/adb/modules/MoveCACerts/system/etc/security/cacerts/重启手机并没有在系统信任证书找到我的证书

**Comment by esingtse** [comment]
> 小米14刷入后无法使用根证书,刷入后把hash.0的文件放入/data/adb/modules/MoveCACerts/system/etc/security/cacerts/重启手机并没有在系统信任证书找到我的证书

兄弟,我也跟你一样,cacerts目录里面有.0的证书,但是系统那里不显示,抓包也都提示certificate_unknown.你是怎么解决的?
